### ISSUE TITLE
Research CSS Framework We'd like to use

### ISSUE THREAD

**Issue by FlikUmbriaco** [ramesh1441/Movies-And-Mixers#6]
User Story:
As a member of the Dev team, I'd like to find a CSS framework to make our webpage look sleek and professional.

Acceptance Criteria:
This step is complete when a CSS framework is chosen and each member of the team is prepared to utilize this framework.

**Comment by Chelsea-Marie** [comment]
Let's do Tailwind!

**Comment by FlikUmbriaco** [comment]
I'm going to build a mock-up over the weekend to show off on monday :)
